[workspace]
members = [
    "crates/checkers-game-app",
]
resolver = "2"

[workspace.package]
authors = ["Сырцев Вадим Игоревич <syrtcevvi@gmail.com>"]
description = "Checkers game written with Rust and Iced"
edition = "2024"

[profile.release]
panic = "abort"
strip = true
lto = true