[package]
name = "checkers-game-app"
authors.workspace = true
description.workspace = true
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1.0.98"
iced = "0.13.1"
itertools = "0.14.0"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
